flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- base-compat-0.9.3
- bytestring-builder-0.10.8.1.0
- font-awesome-type-0.1
- generic-deriving-1.11.2
- nats-1.1.1
- parsec-3.1.11
- regex-1.0.0.0
- regex-base-0.93.2
- regex-posix-0.95.2
- regex-tdfa-1.2.2
- regex-tdfa-text-1.0.0.3
- split-0.2.3.1
- text-show-3.6
- th-lift-0.7.7
- time-locale-compat-0.1.1.3
resolver: ghc-8.0.1
